### ISSUE TITLE
Blocking ports

### ISSUE THREAD

**Issue by jlebrech** [fd0/go-iptables#2]
can this be used to block ports?

**Comment by fd0** [comment]
No, not at the moment. libiptc is able to do that (the iptables-command also uses this library to communicate with the kernel), so it is possible to map the required functions, but I've so far only read the iptables counters with it. 

What is your use case?

**Comment by jlebrech** [comment]
I'm looking to write an app in html5 and WebKit in go, it has to serve on a
port but block it externally and release it when it exits

**Comment by fd0** [comment]
I'll close this issue for now, thanks.
